baseURL = 'https://nshero.github.io'
languageCode = 'en-us'
title = 'this is bad art'
theme = "blank"
enable_toc = false
enable_site_search = true
footer = "Theme by kaiiiz"


[[menu.main]]
  identifier = "about"
  name = "about"
  url = "/about/"
  weight = 1
[[menu.main]]
  identifier = "projects"
  name = "projects"
  url = "/projects/"
  weight = 2
